### PR TITLE
High Resolution Retina Icon for Keyboard

### LINKED ISSUE #1: High Resolution Pakistan Flag in Taskbar
The flag has a white border, and it becomes pixelated on retina screen.

### PR DESCRIPTION
**Pull request by debuggerpk**
The commit fixes #1.

The sketch file is the vector image source file. Sketch can be used to create svgs.
Do we need svgs for other platforms?

### CODE REVIEW

**Comment by debuggerpk** [comment]
please review and accept.

**Comment by KamalAbdali** [comment]
Dear Yousuf Jawwad,
I have no artistic talent, so made something in a hurry (20+ years ago!). Your design is beautiful. I'll
incorporate it, but give me a few days as I am swamped right now.  The merge is a simple step, yet I 
don't want to do it in a hurry. Thanks so much!

Kamal

**Comment by KamalAbdali** [comment]
Dear Yousuf Jawwad,

I had missed your email, and hadn't looked at my Github page until
yesterday. Your high-resolution 256x256 icon is beautiful.

I've a deadline to meet, so I'll get to this matter in a few days. Before
merging your revision, I need to test your icon on two Macs one of which is
a very old Powerbook with a non-retina screen.

Please take a look at the icon _i2u.ico_ in my _InpageToUnicode_ repository
I uploaded yesterday. I had made this icon using Metapost (the code is
in _i2u.mp
http://i2u.mp_) so it can be easily edited like a computer program. I
wonder if there is an official specification of the Pak flag, e.g,
proportion of white/green areas, curves forming the crescent, star size,
etc. If so, one can write an algorithm for it in Metapost or another
similar language.

Can I have your email so as to reach you without going through Github?

I'll get back to you, and thanks much.

Kamal Abdali

**Comment by debuggerpk** [comment]
AA Kamal,

Take our time.

About MetaPost, this is the first time i have read or heard about this programming language. I will look at your i2u.mp file and see if i can contribute to it.

About the specification of Pakistani flag, searching online, i found [this](http://www.pakistani.org/pakistan/flagspec.html).

i can be reached at yousuf@maher.pk

**Comment by KamalAbdali** [comment]
Yousuf Jawwad Saheb,

Wonderful to hear from you.

Thank you unearthing the treasure (Pak flag specs).

Metapost is part of the TeX/LaTeX/XeTeX system. There are several other
similar programs e.g., Asymptote (which I prefer) and Tikz (which is more
popular), but Metapost meshes with TeX better. If the drawing to be made is
simple, Metapost is quite convenient.

If you like adventure and amusement, Metapost is worth looking at. On the
other hand, you might use your time for more important things! I have some
examples of using TeX for Urdu on geomete.com/urdumac.html.

The Pak flag is so nicely specified geometrically that a Metapost program
for it should be easy. If Metapost fascinates you, this flag design is a
nice project, and the program would really be something our compatriots
will appreciate. You don't need to know TeX for this work, as Metapost
programs can be executed by the mpost command directly.  I'm ready to help,
but a bit later.

I recommend these links in addition to the Metapost manual.

http://meeting.contextgarden.net/2008/talks/2008-08-22-hartmut-metapost/mptut-context2008.pdf
http://tex.loria.fr/prod-graph/zoonekynd/metapost/metapost.html

Let's stay in contact.

Best,
Kamal Abdali

**Comment by KamalAbdali** [comment]
Yousuf Jawwad Saheb,

I've encountered two problems:.
1. Since your flag design has no border line, the white area disappears in
   the (normally white) background. So the flag icon on the Mac's top shows
   only the green portion. It doesn't look like the familiar Pak flag. The
   problem can be fixed by adding a thin border line (in black or green)
   around the flag.
2. Dark green color appears almost black in the flag icon on Mac's top bar.
   The problem can be fixed by using a lighter shade of green. This would be a
   compromise with the flag specs but there seems no other choice.

Now about the flag spec as reported in the Letter to Dawn. It refers to the
crescent as "the enclosure between these two arcs". But the text specifies
only the "second arc". It is possible that the letter missed to copy some
text. I suspect that because while the point B has been defined, no further
operation with it is mentioned. Thus B serves no purpose in the quoted
text.

Best,
Kamal Abdali

**Comment by debuggerpk** [comment]
okay let me add the borders and add update the green color. will push the changes once i am done.

**Comment by KamalAbdali** [comment]
Thanks.

Are you going to do more Sherlock to check if there is an official spec of
Pak flag somewhere else?

Kamal

**Pull request closed without merging**
